version: '3.8'

services:
  # Payment Service
  payment-service:
    build: .
    container_name: payment-service
    ports:
      - "8081:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://payment-db:5432/payment_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - payment-db
    networks:
      - ecommerce-network

  # Payment Service Database
  payment-db:
    image: postgres:14-alpine
    container_name: payment-db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=payment_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - payment-db-data:/var/lib/postgresql/data
    networks:
      - ecommerce-network

  # Order Service
  order-service:
    build: ../order-service
    container_name: order-service
    ports:
      - "8082:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://order-db:5432/order_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - order-db
    networks:
      - ecommerce-network

  # Order Service Database
  order-db:
    image: postgres:14-alpine
    container_name: order-db
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_DB=order_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - order-db-data:/var/lib/postgresql/data
    networks:
      - ecommerce-network

  # Product Service
  product-service:
    build: ../product-service
    container_name: product-service
    ports:
      - "8083:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://product-db:5432/product_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - product-db
    networks:
      - ecommerce-network

  # Product Service Database
  product-db:
    image: postgres:14-alpine
    container_name: product-db
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_DB=product_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - product-db-data:/var/lib/postgresql/data
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    driver: bridge

volumes:
  payment-db-data:
  order-db-data:
  product-db-data: