version: '3.8'

services:
  # Order Service
  order-service:
    build:
      context: ..
      dockerfile: docker/local/Dockerfile
    container_name: order-service
    ports:
      - "9092:9092"
      - "5005:5005"  # Debug port
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://order-db:5432/order_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    volumes:
      - ../src:/app/src  # For hot reloading
      - maven-repo:/root/.m2/repository  # Maven cache
    depends_on:
      - order-db
    networks:
      - order-network

  # PostgreSQL Database
  order-db:
    image: postgres:14-alpine
    container_name: order-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=order_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - order-db-data:/var/lib/postgresql/data
    networks:
      - order-network

networks:
  order-network:
    driver: bridge

volumes:
  order-db-data:
  maven-repo:
